OMEDS/urls.py
from django.contrib import admin
from django.urls import path, include
from app import urls as app_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(app_urls)),
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('registration_page/', views.registration_page, name='registration_page'),
    path('registration/', views.registration, name='registration'),
    path('successfull_page/', views.successfull_page, name='successfull_page'),
    path('login_page/', views.login_page, name='login_page'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('account_settings_page/', views.manage_account_page, name='manage_account_page'),
    path('account_deactivation_page/', views.account_deactivation_page, name='account_deactivation_page'),
    path('account_deactivation/', views.account_deactivation, name='account_deactivation'),
    path('account_deletion_page/', views.account_deletion_page, name='account_deletion_page'),
    path('account_deletion/', views.account_deletion, name='account_deletion'),
    path('patient_home_page/', views.patient_home_page, name='patient_home_page'),
    path('patient_profile_page/', views.patient_profile_page, name='patient_profile_page'),
    path('doctor_home_page/', views.doctor_home_page, name='doctor_home_page'),
    path('doctor_profile_page/', views.doctor_profile_page, name='doctor_profile_page'),
    path('home_page/', views.home_page, name='home_page'),
    path('profile_page/', views.profile_page, name='profile_page'),
    path('change_data_page/<str:data_name>/<str:current_data>/', views.change_data_page, name='change_data_page'),
    path('change_data/', views.change_data, name='change_data'),
    path('view_database_page/', views.view_database_page, name='view_database_page'),
    path('view_table_page/<str:table_name>', views.view_table_page, name='view_table_page'),
    path('test_page/', views.test_page, name='test_page'),
]

templates/app/account_deactivation_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/account_deactivation_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/account_deactivation_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}
        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 align="center">Account Deactivation</h1>
            </div>
        </div>

        <div class="jumbotron view-card">
            <div class="jumbotron">
                <p>
                    <h4 class="text-basic" align="center">
                        To <span class="text-dangerous"><b>DE-ACTIVATE</b></span> your account, please enter your password twice.
                    </h4>
                </p>
                <br>
                 {% for alert in alerts %}
                    <div class="alert alert-error alert-dismissible fade show" role="alert">
                        {{ alert }}
                        <button type="button" class="close alert-error-dissmiss-button" data-dismiss="alert" aria-label="Close">
                            &#9932;
                        </button>
                    </div>
                {% endfor %}
                <form class="form-group" action="{% url 'app:account_deactivation' %}" method="post">
                    {% csrf_token %}
                    <p><input class="form-control" id="password" name="password" type="password" placeholder="Password"></p>
                    <p><input class="form-control" id="retype_password" name="retype_password" type="password" placeholder="Retype Password"></p>
                    <br>
                    <input class="btn my_btn btn-block" id="submit" type="submit" value="DEACTIVATE ACCOUNT">
                </form>
            </div>
        </div>

    {% endblock %}

templates/app/change_data_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/change_data_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/change_data_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}
        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 align="center">Change {{ header }}</h1>
            </div>
        </div>

        <div class="jumbotron view-card">
            <div class="jumbotron">

                {% for alert in alerts %}
                    <div class="jumbotron alert-error">
                        &nbsp;&nbsp;&nbsp;{{ alert }}
                    </div>
                {% endfor %}

                <form class="form-group" action="{% url 'app:change_data' %}" method="post">

                    {% csrf_token %}

                    {% if not data_name == "password" %}
                        <p>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text attach-text">
                                        Current {{ header }}:
                                    </div>
                                </div>
                                <input class="form-control view-field" type="text" value="{{ current_data }}" readonly>
                            </div>
                        </p>
                    {% endif %}

                    {% if data_name == "name" %}

                        <p><input class="form-control" id="new_name" name="new_data" type="text" placeholder="New Name" required></p>

                    {% elif data_name == "username" %}

                        <p><input class="form-control" id="new_username" name="new_data" type="text" placeholder="New Username" required></p>

                    {% elif data_name == "email" %}

                        <p><input class="form-control" id="new_email" name="new_data" type="email" placeholder="New Email" required></p>

                    {% elif data_name == "mobile_number" %}

                        <p><input class="form-control" id="new_mobile_number" name="new_data" type="text" placeholder="New Mobile number" required></p>

                    {% elif data_name == "date_of_birth" %}

                        <p>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text attach-text">
                                        Set date of birth to :
                                    </div>
                                </div>
                                <input class="form-control" id="new_date_of_birth" name="new_data" type="date" required>
                            </div>
                        </p>

                    {% elif data_name == "gender" %}

                        <p><input class="form-control" id="new_gender" name="new_data" type="text" placeholder="New Gender" required></p>

                    {% elif data_name == "password" %}

                        <p>
                            <input class="form-control" id="new_password" name="new_data" type="text" placeholder="New Password" required>
                            <small id="passwordHelpBlock" class="form-text text-center text-basic">
                                Your password must be 8-20 characters long, contain letters, special characters and numbers, and must not contain spaces.
                            </small>
                        </p>
                        <p><input class="form-control" id="retype_new_password" name="retype_new_data" type="text" placeholder="Retype new password" required></p>

                    {% endif %}

                    <br>
                    <input class="form-control" id="password" name="password" type="password" placeholder="Password" required>

                    <br>

                    <input id="data_name" name="data_name" type="text" value="{{ data_name }}" hidden readonly>
                    <input name="current_data" type="text" value="{{ current_data }}" hidden readonly>

                    {% if data_name == "password" %}
                        <input class="btn my_btn btn-block" id="submit" name="submit" type="submit" value="Change" disabled>
                    {% else %}
                        <input class="btn my_btn btn-block" id="submit" name="submit" type="submit" value="Change">
                    {% endif %}

                </form>
            </div>
        </div>

    {% endblock %}

templates/app/doctor_home_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/doctor_home_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/doctor_home_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}

        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 align="center">Welcome {{ logged_in_username }}</h1>
            </div>
        </div>

        <div class="jumbotron">
            <div class="row">
                <div class="col">
                    <a class="btn my_btn btn-block" href="{% url 'app:doctor_home_page' %}">Set and Manage Schedules</a>
                </div>
                <div class="col">
                    <a class="btn my_btn btn-block" href="{% url 'app:doctor_home_page' %}">Check/Withdraw Balance</a>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col">
                    <a class="btn my_btn btn-block" href="{% url 'app:doctor_home_page' %}">My Online Chamber</a>
                </div>
                <div class="col">
                    <a class="btn my_btn btn-block" href="{% url 'app:doctor_home_page' %}">History</a>
                </div>
            </div>
        </div>
    {% endblock %}

templates/app/doctor_profile_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/doctor_profile_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/doctor_profile_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}
        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 align="center">Profile</h1>
            </div>
        </div>

        <div class="jumbotron view-card">

            {% for alert in alerts %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ alert }}
                    <button type="button" class="close alert-success-dissmiss-button" data-dismiss="alert" aria-label="Close">
                        &#9932;
                    </button>
                </div>
            {% endfor %}

            <div class="jumbotron">
                {% for user_datum in user_data %}

                    <p>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="attach-text input-group-text">
                                    {{ user_datum.0 }}
                                </div>
                            </div>

                            <input class="form-control view-field" type="text" value="{{ user_datum.1 }}" readonly>

                            <div class="input-group-append">
                                <div class="input-group-text attach-text-link">
                                    <a href="{% url 'app:change_data_page' user_datum.2 user_datum.1 %}">Edit or change</a>
                                </div>
                            </div>
                        </div>
                    </p>

                {% endfor %}
            </div>
        </div>

    {% endblock %}

templates/app/login_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/login_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/login_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}

        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 align="center">Login</h1>
            </div>
        </div>

        <div class="jumbotron" id="login-card">
            <div class="jumbotron">

                {% for alert in alerts %}
                    <div class="alert alert-error alert-dismissible fade show" role="alert">
                        {{ alert }}
                        <button type="button" class="close alert-error-dissmiss-button" data-dismiss="alert" aria-label="Close">
                            &#9932;
                        </button>
                    </div>
                {% endfor %}

                <form class="form-group" action="{% url 'app:login' %}" method="post">
                    {% csrf_token %}

                    <p><input class="form-control" id="username" name="username" type="text" value="{{ username }}" placeholder="Username" required></p>
                    <p><input class="form-control" id="password" name="password" type="password" placeholder="Password" required></p>

                    <br>

                    <input class="btn my_btn btn-block " id="submit" type="submit" value="Login">
                </form>
            </div>
        </div>


    {% endblock %}

templates/app/manage_account_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/manage_account_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/manage_account_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}
        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 align="center">Manage Account</h1>
            </div>
        </div>
        <div class="jumbotron view-card">
            <div class="jumbotron">
                <a class="btn my_btn btn-block" href="{% url 'app:change_data_page' 'password' 'null' %}">Change Password</a>
                <a class="btn my_btn btn-block" href="{% url 'app:account_deactivation_page' %}">De-activate Account</a>
                <a class="btn my_btn btn-block" href="{% url 'app:account_deletion_page' %}">Delete Account</a>
            </div>
        </div>
    {% endblock %}

templates/app/page_template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        {% block additions %}{% endblock %}
            <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="{% static 'app/css/page_template.css' %}">
        {% block my_stylesheet %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'app:landing_page' %}"><b>OMEDS</b></a>

{#                <ul class="navbar-nav mr-auto">#}
{#                    <li class="nav-item"><a class="nav-link" href="{% url 'app:test_page' %}">Test Page</a></li>#}
{#                    <li class="nav-item"><a class="nav-link" href="{% url 'app:view_database_page' %}">View Database</a></li>#}
{#                </ul>#}

                <ul class="navbar-nav justify-content-end">
                    {% if login_status == "true" %}
                        <li class="nav-item">
                            <div class="input-group">
                                <div class="input-group-prepend" id="logged_in_username">
                                    <div class="input-group-text attach-text">
                                        <a id="logged_in_user_name" href="{% url 'app:home_page' %}"><b>{{ logged_in_username }}</b></a>
                                    </div>
                                </div>
                                <div class="dropdown">
                                    <button class="form-control btn dropdown-toggle" id="logged_in_user_options" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuOffset">
                                        <a class="dropdown-item" href="{% url 'app:profile_page' %}">Profile</a>
                                        {% if user_type == "patient" %}
                                            <a class="dropdown-item" href="{% url 'app:home_page' %}">Wallet</a>
                                        {% endif %}
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'app:manage_account_page' %}">Manage Account</a>
                                        <a class="dropdown-item" href="{% url 'app:logout' %}">Logout</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endif %}
                    {% if page_name == "registration_page" %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'app:login_page' %}">Login</a></li>
                    {% elif page_name == "login_page" %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'app:registration_page' %}">Register</a></li>
                    {% endif %}
                </ul>

            </div>
        </nav>
        <br>
        <div class="container">
            <br><br>
            <style>
                body {
                    background-image: url("{% static 'app/img/background-4.jpg' %}");
                    background-size: cover;
                }
            </style>
            {% block main_block %}{% endblock %}
        </div>
        <script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        {% block my_script %}{% endblock %}
    </body>
</html>

templates/app/patient_home_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/patient_home_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/patient_home_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}

        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 align="center">Welcome {{ logged_in_username }}</h1>
            </div>
        </div>

        <div class="jumbotron">
            <div class="row">
                <div class="col">
                    <a class="btn my_btn btn-block" href="{% url 'app:patient_home_page' %}">Visit a Doctor</a>
                </div>
                <div class="col">
                    <a class="btn my_btn btn-block" href="{% url 'app:patient_home_page' %}">Prescriptions</a>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col">
                    <a class="btn my_btn btn-block" href="{% url 'app:patient_home_page' %}">Appointments</a>
                </div>
                <div class="col">
                    <a class="btn my_btn btn-block" href="{% url 'app:patient_home_page' %}">Medicine Schedules</a>
                </div>
            </div>
        </div>
    {% endblock %}

templates/app/patient_profile_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/patient_profile_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/patient_profile_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}
        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 align="center">Profile</h1>
            </div>
        </div>

        <div class="jumbotron view-card">

            {% for alert in alerts %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ alert }}
                    <button type="button" class="close alert-success-dissmiss-button" data-dismiss="alert" aria-label="Close">
                        &#9932;
                    </button>
                </div>
            {% endfor %}

            <div class="jumbotron">
                {% for user_datum in user_data %}

                    <p>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="attach-text input-group-text">
                                    {{ user_datum.0 }}
                                </div>
                            </div>

                            <input class="form-control view-field" type="text" value="{{ user_datum.1 }}" readonly>

                            <div class="input-group-append">
                                <div class="input-group-text attach-text-link">
                                    <a href="{% url 'app:change_data_page' data_name=user_datum.2 current_data=user_datum.1 %}">Edit or change</a>
                                </div>
                            </div>
                        </div>
                    </p>

                {% endfor %}
            </div>
        </div>
    {% endblock %}

templates/app/registration_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/registration_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/registration_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}

        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 align="center">Registration</h1>
            </div>
        </div>

        {% for alert in alerts %}
            <div class="alert alert-error alert-dismissible fade show" role="alert">
                {{ alert }}
                <button type="button" class="close alert-error-dissmiss-button" data-dismiss="alert" aria-label="Close">
                    &#9932;
                </button>
            </div>
        {% endfor %}

        <div class="jumbotron">

            <form class="form-group" action="{% url 'app:registration' %}" method="post">

                {% csrf_token %}

                <p>
                    <select class="form-control" name="user_type" id="user_type">
                        <option value="null" selected>Select your user type</option>
                        <div class="custom_select_option">
                            <option value="general_user">General User</option>
                        </div>
                        <option value="doctor">Doctor</option>
                    </select>
                </p>

                <p><input class="form-control" id="name" name="name" type="text" value="{{ name }}" placeholder="Full Name" required></p>

                <p><input class="form-control" id="username" name="username" type="text" value="{{ username }}" placeholder="Username" required></p>

                <p><input class="form-control" id="email" name="email" type="email" value="{{ email }}" placeholder="Email" required></p>

                <p><input class="form-control" id="mobile_no" name="mobile_no" type="text" value="{{ mobile_no }}" placeholder="Mobile No." required></p>

                <p>
                    <div class="row">
                        <div class="col">
                            <input class="form-control" id="password" name="password" type="text" value="{{ password }}" placeholder="Password" required>
                        </div>
                        <div class="col">
                            <input class="form-control" id="retype_password" name="retype_password" type="text" value="{{ retype_password }}" placeholder="Retype Password" required>
                        </div>
                    </div>
                    <small id="passwordHelpBlock" class="form-text text-center text-basic">
                        Your password must be 8-20 characters long, contain letters, special characters and numbers, and must not contain spaces.
                    </small>
                </p>

                <p>
                    <div class="row">
                        <div class="col">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="attach-text input-group-text">Select your date of birth:</div>
                                </div>
                                <input class="form-control" id="date_of_birth" name="date_of_birth" type="date" value="{{ date_of_birth }}" required>
                            </div>
                        </div>
                        <div class="col">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="attach-text input-group-text">Select your Gender:</div>
                                </div>
                                <select class="form-control" name="gender" id="gender">
                                    <option value="male" selected>Male</option>
                                    <option value="female">Female</option>
                                </select>
                            </div>
                        </div>
                    </div>

                </p>

                <br>

                <input class="btn my_btn btn-block" id="submit" type="submit" value="Submit" disabled>

            </form>
        </div>

    {% endblock %}

templates/app/successfull_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/successfull_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/successfull_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}
        <br><br><br>
        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 class="text-center">Registration Successfull !!!</h1>
            </div>
        </div>

        <div class="view-card">
            <a class="btn my_btn btn-block" href="{% url 'app:login_page' %}">Login</a>
        </div>

    {% endblock %}

templates/app/test_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        Testing OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/test_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/test_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}
    <input type="password" id="inputPassword5" class="form-control" aria-describedby="passwordHelpBlock">
    <small id="passwordHelpBlock" class="form-text text-muted">
        Your password must be 8-20 characters long, contain letters, special characters and numbers, and must not contain spaces.
    </small>
    {% endblock %}

templates/app/view_database_page.html
{% extends 'app/page_template.html' %}

    {% load static %}

    {% block title %}
        OMEDS
    {% endblock %}

    {% block additions %}

    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static 'app/css/view_database_page.css' %}">
    {% endblock %}

    {% block my_script %}
        <script src="{% static 'app/js/view_database_page.js' %}"></script>
    {% endblock %}

    {% block main_block %}
        <div class="jumbotron header_layer_1">
            <div class="jumbotron header_layer_2">
                <h1 align="center">Select a table</h1>
            </div>
        </div>

        <div class="jumbotron view-card">
            <div class="jumbotron">
                {% for table_name in table_names %}
                    <a class="btn my_btn btn-block" href="{% url 'app:view_table_page' table_name %}">{{ table_name }}</a>
                {% endfor %}
            </div>
        </div>
    {% endblock %}